// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 000001_init_mg.down.sql (339B)
// 000001_init_mg.up.sql (339B)
// 000002_init_mg.down.sql (336B)
// 000002_init_mg.up.sql (336B)

package bindata

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\xcd\x6e\x83\x30\x10\x84\xef\x3c\xc5\x1e\x41\xe2\x40\xd5\x23\x27\x17\x96\xd6\x2a\x6d\xd1\x62\xaa\x70\x8a\x08\xc6\x0e\x8a\x63\x22\x7e\xde\x3f\x52\x44\x90\x40\xe4\xfa\xcd\xcc\xee\x17\xd3\x5f\x06\x82\x7d\xa4\x08\x3c\x01\x3c\xf0\x5c\xe4\x30\x9c\xbb\x7e\x3c\x9a\xce\xea\x82\xd2\xd0\xd9\xed\xd4\x4a\x87\x4e\x44\xc8\x04\xce\xd9\x6a\x05\x6e\x2b\x81\xff\x0a\xfc\x44\x82\x8c\xf8\x0f\xa3\x12\xbe\xb1\xf4\xe7\xda\xd4\x1b\xf8\x67\x14\x7d\x31\x72\xdf\x82\xc0\xf3\xe1\x39\x5c\xd3\xb1\xbb\x34\x76\x61\xef\x0f\x26\x1b\x93\x98\x4a\x2f\xe7\x63\x4c\x58\x91\x0a\x08\xbc\x8d\x51\xad\xf4\x6b\x0f\x65\x2a\x4d\x93\x65\x52\xf6\x9b\x9f\xd5\xad\xdd\x0f\x94\xb1\xd7\xad\xdf\x30\x9c\x56\xc8\x0b\xef\x01\x00\x00\xff\xff\x7a\xcb\x46\xe1\x53\x01\x00\x00")

func _000001_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgDownSql,
		"000001_init_mg.down.sql",
	)
}

func _000001_init_mgDownSql() (*asset, error) {
	bytes, err := _000001_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.down.sql", size: 339, mode: os.FileMode(0644), modTime: time.Unix(1722274359, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb6, 0x3f, 0xfd, 0xf2, 0x45, 0xc7, 0x5c, 0x14, 0xf9, 0x9a, 0xcb, 0x46, 0xa4, 0x54, 0xbf, 0xf1, 0x58, 0x21, 0x81, 0xe3, 0x64, 0x34, 0xe6, 0x95, 0x34, 0xdd, 0x9b, 0xf7, 0x56, 0x29, 0xb, 0x6c}}
	return a, nil
}

var __000001_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\xcd\x6e\x83\x30\x10\x84\xef\x3c\xc5\x1e\x41\xe2\x40\xd5\x23\x27\x17\x96\xd6\x2a\x6d\xd1\x62\xaa\x70\x8a\x08\xc6\x0e\x8a\x63\x22\x7e\xde\x3f\x52\x44\x90\x40\xe4\xfa\xcd\xcc\xee\x17\xd3\x5f\x06\x82\x7d\xa4\x08\x3c\x01\x3c\xf0\x5c\xe4\x30\x9c\xbb\x7e\x3c\x9a\xce\xea\x82\xd2\xd0\xd9\xed\xd4\x4a\x87\x4e\x44\xc8\x04\xce\xd9\x6a\x05\x6e\x2b\x81\xff\x0a\xfc\x44\x82\x8c\xf8\x0f\xa3\x12\xbe\xb1\xf4\xe7\xda\xd4\x1b\xf8\x67\x14\x7d\x31\x72\xdf\x82\xc0\xf3\xe1\x39\x5c\xd3\xb1\xbb\x34\x76\x61\xef\x0f\x26\x1b\x93\x98\x4a\x2f\xe7\x63\x4c\x58\x91\x0a\x08\xbc\x8d\x51\xad\xf4\x6b\x0f\x65\x2a\x4d\x93\x65\x52\xf6\x9b\x9f\xd5\xad\xdd\x0f\x94\xb1\xd7\xad\xdf\x30\x9c\x56\xc8\x0b\xef\x01\x00\x00\xff\xff\x7a\xcb\x46\xe1\x53\x01\x00\x00")

func _000001_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgUpSql,
		"000001_init_mg.up.sql",
	)
}

func _000001_init_mgUpSql() (*asset, error) {
	bytes, err := _000001_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.up.sql", size: 339, mode: os.FileMode(0644), modTime: time.Unix(1722274377, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb6, 0x3f, 0xfd, 0xf2, 0x45, 0xc7, 0x5c, 0x14, 0xf9, 0x9a, 0xcb, 0x46, 0xa4, 0x54, 0xbf, 0xf1, 0x58, 0x21, 0x81, 0xe3, 0x64, 0x34, 0xe6, 0x95, 0x34, 0xdd, 0x9b, 0xf7, 0x56, 0x29, 0xb, 0x6c}}
	return a, nil
}

var __000002_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x4d\x4b\x86\x40\x14\x85\xf7\xef\xaf\xb8\x4b\x05\x17\x46\x4b\x57\x37\xbd\xd6\xd0\x54\x72\x1d\x23\x57\x61\x8e\x33\x49\xd3\x18\x7e\xfc\xff\x20\x24\x70\xf0\xdd\x3e\xe7\x1c\xce\x53\xf0\x4b\x05\x0a\xef\x24\x81\x28\x81\xde\x44\xad\x6a\x58\x3e\xa7\x79\x7d\x77\x93\xb7\x0d\xcb\xec\x72\xda\xe9\x8d\xcd\x2e\x39\x13\x2a\xda\xb3\xc3\x2a\x1a\x35\xd4\xc4\x02\x25\x54\x2c\x9e\x90\x5b\x78\xa4\x36\xd9\x4b\xdb\xec\xe0\x15\x39\x7f\x40\x8e\x6e\xd2\x34\x4e\x60\x9f\x05\x74\x9d\xbe\x06\xff\xcf\x6e\xff\x98\x1e\x5c\xe9\x3a\x0b\xe2\x59\xd1\x3d\x31\x14\x54\x62\x23\x15\xa4\x71\xe0\xd3\x1b\x0b\xd7\x34\x8c\xeb\x2c\x6f\x1e\xb5\x9e\x83\xcb\xee\x67\x3c\x0f\x8c\xf3\xdf\xa1\xde\xb2\x7c\x1c\x50\x9c\xfd\x06\x00\x00\xff\xff\x86\xbd\x75\xb4\x50\x01\x00\x00")

func _000002_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgDownSql,
		"000002_init_mg.down.sql",
	)
}

func _000002_init_mgDownSql() (*asset, error) {
	bytes, err := _000002_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.down.sql", size: 336, mode: os.FileMode(0644), modTime: time.Unix(1722274391, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x90, 0x13, 0xa5, 0x6f, 0xd4, 0x6f, 0xf, 0x61, 0x1c, 0xa8, 0x74, 0x41, 0x82, 0x78, 0x34, 0xb7, 0x84, 0x36, 0x8, 0x2b, 0xd8, 0x9f, 0xf5, 0xea, 0xb3, 0x4c, 0xee, 0x69, 0x38, 0xb, 0x9e, 0xe2}}
	return a, nil
}

var __000002_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x4d\x4b\x86\x40\x14\x85\xf7\xef\xaf\xb8\x4b\x05\x17\x46\x4b\x57\x37\xbd\xd6\xd0\x54\x72\x1d\x23\x57\x61\x8e\x33\x49\xd3\x18\x7e\xfc\xff\x20\x24\x70\xf0\xdd\x3e\xe7\x1c\xce\x53\xf0\x4b\x05\x0a\xef\x24\x81\x28\x81\xde\x44\xad\x6a\x58\x3e\xa7\x79\x7d\x77\x93\xb7\x0d\xcb\xec\x72\xda\xe9\x8d\xcd\x2e\x39\x13\x2a\xda\xb3\xc3\x2a\x1a\x35\xd4\xc4\x02\x25\x54\x2c\x9e\x90\x5b\x78\xa4\x36\xd9\x4b\xdb\xec\xe0\x15\x39\x7f\x40\x8e\x6e\xd2\x34\x4e\x60\x9f\x05\x74\x9d\xbe\x06\xff\xcf\x6e\xff\x98\x1e\x5c\xe9\x3a\x0b\xe2\x59\xd1\x3d\x31\x14\x54\x62\x23\x15\xa4\x71\xe0\xd3\x1b\x0b\xd7\x34\x8c\xeb\x2c\x6f\x1e\xb5\x9e\x83\xcb\xee\x67\x3c\x0f\x8c\xf3\xdf\xa1\xde\xb2\x7c\x1c\x50\x9c\xfd\x06\x00\x00\xff\xff\x86\xbd\x75\xb4\x50\x01\x00\x00")

func _000002_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgUpSql,
		"000002_init_mg.up.sql",
	)
}

func _000002_init_mgUpSql() (*asset, error) {
	bytes, err := _000002_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.up.sql", size: 336, mode: os.FileMode(0644), modTime: time.Unix(1722274411, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x90, 0x13, 0xa5, 0x6f, 0xd4, 0x6f, 0xf, 0x61, 0x1c, 0xa8, 0x74, 0x41, 0x82, 0x78, 0x34, 0xb7, 0x84, 0x36, 0x8, 0x2b, 0xd8, 0x9f, 0xf5, 0xea, 0xb3, 0x4c, 0xee, 0x69, 0x38, 0xb, 0x9e, 0xe2}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init_mg.down.sql": _000001_init_mgDownSql,
	"000001_init_mg.up.sql":   _000001_init_mgUpSql,
	"000002_init_mg.down.sql": _000002_init_mgDownSql,
	"000002_init_mg.up.sql":   _000002_init_mgUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init_mg.down.sql": {_000001_init_mgDownSql, map[string]*bintree{}},
	"000001_init_mg.up.sql":   {_000001_init_mgUpSql, map[string]*bintree{}},
	"000002_init_mg.down.sql": {_000002_init_mgDownSql, map[string]*bintree{}},
	"000002_init_mg.up.sql":   {_000002_init_mgUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
