// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 000001_init_mg.down.sql (319B)
// 000001_init_mg.up.sql (319B)
// 000002_init_mg.down.sql (316B)
// 000002_init_mg.up.sql (316B)

package bindata

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x31\x8f\x82\x40\x10\x85\x7b\x7e\xc5\x94\x90\x50\x70\xb9\x92\x6a\x0f\x86\x73\x23\x2a\x19\x16\x23\x95\x21\xac\xbb\x12\x57\x30\x08\xff\xdf\x68\x90\x08\xc1\xf6\x7b\xef\xcd\x7c\x21\xed\x12\x10\xec\x2f\x46\xe0\x11\xe0\x81\xa7\x22\x85\xfb\xb9\x69\xbb\xa3\x69\x6a\x9d\x51\xec\x5b\x8b\x9d\x52\x69\xdf\x0a\x08\x99\xc0\x21\x9b\xac\xc0\xae\x24\xf0\xad\xc0\x7f\x24\x48\x88\x6f\x18\xe5\xb0\xc6\xdc\x1d\x6a\x7d\x6b\x60\xcf\x28\x58\x31\xb2\x7f\x3c\xcf\x71\xe1\x3d\x9c\xd2\xee\x52\x5f\x47\xf4\xfb\x42\xf2\x64\x22\x53\xe8\xf1\x7a\x88\x11\xcb\x62\x01\x9e\x33\x13\x2a\x95\xfe\xae\xa1\x4c\xa1\xa9\xaf\x99\x94\xed\xec\x65\x71\xab\x96\x03\x65\x3e\x5c\x9e\xc8\xf1\x1f\x01\x00\x00\xff\xff\x38\xf2\xb7\xd5\x3f\x01\x00\x00")

func _000001_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgDownSql,
		"000001_init_mg.down.sql",
	)
}

func _000001_init_mgDownSql() (*asset, error) {
	bytes, err := _000001_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.down.sql", size: 319, mode: os.FileMode(0644), modTime: time.Unix(1713731319, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x27, 0x2c, 0x52, 0xaf, 0x14, 0xd8, 0x93, 0xcf, 0x6c, 0xe, 0x62, 0x71, 0x18, 0x6d, 0x9e, 0xa7, 0x67, 0x6a, 0x80, 0xf3, 0xb8, 0x96, 0x30, 0x39, 0x38, 0x41, 0xae, 0xb2, 0xe8, 0x4, 0xe0, 0xe5}}
	return a, nil
}

var __000001_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x31\x8f\x82\x40\x10\x85\x7b\x7e\xc5\x94\x90\x50\x70\xb9\x92\x6a\x0f\x86\x73\x23\x2a\x19\x16\x23\x95\x21\xac\xbb\x12\x57\x30\x08\xff\xdf\x68\x90\x08\xc1\xf6\x7b\xef\xcd\x7c\x21\xed\x12\x10\xec\x2f\x46\xe0\x11\xe0\x81\xa7\x22\x85\xfb\xb9\x69\xbb\xa3\x69\x6a\x9d\x51\xec\x5b\x8b\x9d\x52\x69\xdf\x0a\x08\x99\xc0\x21\x9b\xac\xc0\xae\x24\xf0\xad\xc0\x7f\x24\x48\x88\x6f\x18\xe5\xb0\xc6\xdc\x1d\x6a\x7d\x6b\x60\xcf\x28\x58\x31\xb2\x7f\x3c\xcf\x71\xe1\x3d\x9c\xd2\xee\x52\x5f\x47\xf4\xfb\x42\xf2\x64\x22\x53\xe8\xf1\x7a\x88\x11\xcb\x62\x01\x9e\x33\x13\x2a\x95\xfe\xae\xa1\x4c\xa1\xa9\xaf\x99\x94\xed\xec\x65\x71\xab\x96\x03\x65\x3e\x5c\x9e\xc8\xf1\x1f\x01\x00\x00\xff\xff\x38\xf2\xb7\xd5\x3f\x01\x00\x00")

func _000001_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgUpSql,
		"000001_init_mg.up.sql",
	)
}

func _000001_init_mgUpSql() (*asset, error) {
	bytes, err := _000001_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.up.sql", size: 319, mode: os.FileMode(0644), modTime: time.Unix(1713731323, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x27, 0x2c, 0x52, 0xaf, 0x14, 0xd8, 0x93, 0xcf, 0x6c, 0xe, 0x62, 0x71, 0x18, 0x6d, 0x9e, 0xa7, 0x67, 0x6a, 0x80, 0xf3, 0xb8, 0x96, 0x30, 0x39, 0x38, 0x41, 0xae, 0xb2, 0xe8, 0x4, 0xe0, 0xe5}}
	return a, nil
}

var __000002_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x6b\x83\x40\x10\x85\xef\xfe\x8a\x39\x2a\x78\xb0\xf4\xe8\x69\xaa\x63\xbb\x74\xdb\xca\xb8\x96\x78\x0a\xe2\x66\x37\x92\x8d\x06\xa3\xff\x3f\x24\x48\x48\xc4\x5c\xbf\xf7\x1e\xef\x4b\xf9\x2f\x07\x85\x1f\x92\x40\x64\x40\x1b\x51\xa8\x02\xce\xfb\x7e\x18\xb7\xae\xef\x6c\xc9\x32\xf6\x56\x3b\x8d\xb1\xb1\x97\x30\xa1\xa2\x39\x7b\x5a\xf9\xad\x86\x82\x58\xa0\x84\x9c\xc5\x0f\x72\x05\xdf\x54\x85\x73\x69\x1a\x1c\xfc\x23\x27\x5f\xc8\xfe\x5b\x14\x05\x21\xcc\xb3\x05\x1d\x0f\xdd\xf1\x8e\xde\x6f\x48\xef\x5c\xe6\x6a\x0b\xe2\x57\xd1\x27\x31\xa4\x94\x61\x29\x15\x44\xc1\x42\xa7\x31\x16\x5e\x59\x18\x57\x5b\x9e\x3a\xd4\x7a\x58\x3c\xd6\xa7\x76\x3d\x30\xee\x41\xe5\x8a\x82\xf8\x12\x00\x00\xff\xff\x9c\x9a\xe4\xb6\x3c\x01\x00\x00")

func _000002_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgDownSql,
		"000002_init_mg.down.sql",
	)
}

func _000002_init_mgDownSql() (*asset, error) {
	bytes, err := _000002_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.down.sql", size: 316, mode: os.FileMode(0644), modTime: time.Unix(1713731312, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8a, 0x6d, 0x15, 0xb, 0xe0, 0x8, 0x56, 0xd0, 0x8, 0x3d, 0xc5, 0x6c, 0x73, 0x4d, 0xf6, 0xdc, 0x6e, 0xd0, 0x6e, 0x5d, 0x18, 0xbe, 0xfd, 0xc3, 0x65, 0xfd, 0xf7, 0x12, 0x45, 0xe0, 0xd8, 0xdf}}
	return a, nil
}

var __000002_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x6b\x83\x40\x10\x85\xef\xfe\x8a\x39\x2a\x78\xb0\xf4\xe8\x69\xaa\x63\xbb\x74\xdb\xca\xb8\x96\x78\x0a\xe2\x66\x37\x92\x8d\x06\xa3\xff\x3f\x24\x48\x48\xc4\x5c\xbf\xf7\x1e\xef\x4b\xf9\x2f\x07\x85\x1f\x92\x40\x64\x40\x1b\x51\xa8\x02\xce\xfb\x7e\x18\xb7\xae\xef\x6c\xc9\x32\xf6\x56\x3b\x8d\xb1\xb1\x97\x30\xa1\xa2\x39\x7b\x5a\xf9\xad\x86\x82\x58\xa0\x84\x9c\xc5\x0f\x72\x05\xdf\x54\x85\x73\x69\x1a\x1c\xfc\x23\x27\x5f\xc8\xfe\x5b\x14\x05\x21\xcc\xb3\x05\x1d\x0f\xdd\xf1\x8e\xde\x6f\x48\xef\x5c\xe6\x6a\x0b\xe2\x57\xd1\x27\x31\xa4\x94\x61\x29\x15\x44\xc1\x42\xa7\x31\x16\x5e\x59\x18\x57\x5b\x9e\x3a\xd4\x7a\x58\x3c\xd6\xa7\x76\x3d\x30\xee\x41\xe5\x8a\x82\xf8\x12\x00\x00\xff\xff\x9c\x9a\xe4\xb6\x3c\x01\x00\x00")

func _000002_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgUpSql,
		"000002_init_mg.up.sql",
	)
}

func _000002_init_mgUpSql() (*asset, error) {
	bytes, err := _000002_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.up.sql", size: 316, mode: os.FileMode(0644), modTime: time.Unix(1713731315, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8a, 0x6d, 0x15, 0xb, 0xe0, 0x8, 0x56, 0xd0, 0x8, 0x3d, 0xc5, 0x6c, 0x73, 0x4d, 0xf6, 0xdc, 0x6e, 0xd0, 0x6e, 0x5d, 0x18, 0xbe, 0xfd, 0xc3, 0x65, 0xfd, 0xf7, 0x12, 0x45, 0xe0, 0xd8, 0xdf}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init_mg.down.sql": _000001_init_mgDownSql,
	"000001_init_mg.up.sql":   _000001_init_mgUpSql,
	"000002_init_mg.down.sql": _000002_init_mgDownSql,
	"000002_init_mg.up.sql":   _000002_init_mgUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init_mg.down.sql": {_000001_init_mgDownSql, map[string]*bintree{}},
	"000001_init_mg.up.sql":   {_000001_init_mgUpSql, map[string]*bintree{}},
	"000002_init_mg.down.sql": {_000002_init_mgDownSql, map[string]*bintree{}},
	"000002_init_mg.up.sql":   {_000002_init_mgUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
