// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 000001_init_mg.down.sql (320B)
// 000001_init_mg.up.sql (320B)
// 000002_init_mg.down.sql (317B)
// 000002_init_mg.up.sql (317B)

package bindata

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x8b\x83\x30\x10\x85\xef\xfe\x8a\x39\x2a\x78\x70\xd9\xa3\xa7\xac\x8e\xbb\x61\x6d\x2b\x63\x2c\xf5\x54\xc4\x98\x54\x9a\xc6\x62\xf5\xff\x17\x8a\x15\x14\x7b\xfd\xde\x7b\x33\x5f\x4c\x87\x0c\x04\xfb\x49\x11\x78\x02\x78\xe2\xb9\xc8\xe1\x71\xe9\xfa\xe1\x6c\x3a\xab\x0b\x4a\x43\x67\xb3\x53\x2b\x1d\x3a\x11\x21\x13\x38\x65\x8b\x15\xb8\xad\x04\xbe\x17\xf8\x8b\x04\x19\xf1\x1d\xa3\x12\xfe\xb1\xf4\xa7\xda\xd8\x1b\x38\x32\x8a\xfe\x18\xb9\x5f\x41\xe0\xf9\xf0\x1e\x2e\xe9\xd0\x5d\x1b\x3b\xb3\xef\x17\x93\x8d\x49\x4c\xa5\xe7\xf3\x31\x26\xac\x48\x05\x04\xde\xca\xa8\x56\xfa\xb3\x87\x32\x95\xa6\xd1\x32\x29\xfb\xd5\xcf\xea\xde\x6e\x07\xca\xd8\xdb\x02\x79\xe1\x33\x00\x00\xff\xff\x76\x3d\x81\x80\x40\x01\x00\x00")

func _000001_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgDownSql,
		"000001_init_mg.down.sql",
	)
}

func _000001_init_mgDownSql() (*asset, error) {
	bytes, err := _000001_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.down.sql", size: 320, mode: os.FileMode(0644), modTime: time.Unix(1714086770, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xc2, 0xee, 0xf4, 0x1, 0x1a, 0x76, 0x95, 0x3f, 0x34, 0x7d, 0xb9, 0x42, 0xb1, 0xef, 0x3d, 0xbd, 0x30, 0x6d, 0x72, 0x71, 0xd0, 0x25, 0x37, 0x72, 0x82, 0x8d, 0x7a, 0x3c, 0x7c, 0x3c, 0xc6, 0xb6}}
	return a, nil
}

var __000001_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x8b\x83\x30\x10\x85\xef\xfe\x8a\x39\x2a\x78\x70\xd9\xa3\xa7\xac\x8e\xbb\x61\x6d\x2b\x63\x2c\xf5\x54\xc4\x98\x54\x9a\xc6\x62\xf5\xff\x17\x8a\x15\x14\x7b\xfd\xde\x7b\x33\x5f\x4c\x87\x0c\x04\xfb\x49\x11\x78\x02\x78\xe2\xb9\xc8\xe1\x71\xe9\xfa\xe1\x6c\x3a\xab\x0b\x4a\x43\x67\xb3\x53\x2b\x1d\x3a\x11\x21\x13\x38\x65\x8b\x15\xb8\xad\x04\xbe\x17\xf8\x8b\x04\x19\xf1\x1d\xa3\x12\xfe\xb1\xf4\xa7\xda\xd8\x1b\x38\x32\x8a\xfe\x18\xb9\x5f\x41\xe0\xf9\xf0\x1e\x2e\xe9\xd0\x5d\x1b\x3b\xb3\xef\x17\x93\x8d\x49\x4c\xa5\xe7\xf3\x31\x26\xac\x48\x05\x04\xde\xca\xa8\x56\xfa\xb3\x87\x32\x95\xa6\xd1\x32\x29\xfb\xd5\xcf\xea\xde\x6e\x07\xca\xd8\xdb\x02\x79\xe1\x33\x00\x00\xff\xff\x76\x3d\x81\x80\x40\x01\x00\x00")

func _000001_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgUpSql,
		"000001_init_mg.up.sql",
	)
}

func _000001_init_mgUpSql() (*asset, error) {
	bytes, err := _000001_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.up.sql", size: 320, mode: os.FileMode(0644), modTime: time.Unix(1714086770, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xc2, 0xee, 0xf4, 0x1, 0x1a, 0x76, 0x95, 0x3f, 0x34, 0x7d, 0xb9, 0x42, 0xb1, 0xef, 0x3d, 0xbd, 0x30, 0x6d, 0x72, 0x71, 0xd0, 0x25, 0x37, 0x72, 0x82, 0x8d, 0x7a, 0x3c, 0x7c, 0x3c, 0xc6, 0xb6}}
	return a, nil
}

var __000002_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x6b\x84\x30\x10\x85\xef\xfe\x8a\x39\x2a\x78\xb0\xf4\xe8\x69\xaa\x63\x1b\x9a\xb6\x32\xc6\x52\x4f\x45\x8c\x49\xa5\xd9\xb8\xb8\xfa\xff\x17\x16\x59\x50\xdc\xeb\xf7\xde\xe3\x7d\x39\x7f\x95\xa0\xf0\x45\x12\x88\x02\xe8\x47\x54\xaa\x82\xcb\xdf\x38\xcd\xbf\x6e\xf4\xb6\x66\x99\x06\x87\x9d\xce\xd8\x34\xc8\x98\x50\xd1\x9a\x6d\x56\xe1\xa0\xa1\x22\x16\x28\xa1\x64\xf1\x81\xdc\xc0\x3b\x35\xf1\x5a\x5a\x26\x07\xdf\xc8\xd9\x1b\x72\xf8\x94\x24\x51\x0c\xeb\x6c\x47\xe7\xf1\xbf\xf7\x77\xf6\x7c\x63\xba\x77\x85\x6b\x2d\x88\x4f\x45\xaf\xc4\x90\x53\x81\xb5\x54\x90\x44\x3b\x9f\xce\x58\x78\xa4\x61\x5c\x6b\x79\xf1\xa8\xf5\xb4\xbb\x6c\xcf\xc3\x71\x60\x9c\x3f\x6d\x50\x94\x5e\x03\x00\x00\xff\xff\x4b\x59\xac\x82\x3d\x01\x00\x00")

func _000002_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgDownSql,
		"000002_init_mg.down.sql",
	)
}

func _000002_init_mgDownSql() (*asset, error) {
	bytes, err := _000002_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.down.sql", size: 317, mode: os.FileMode(0644), modTime: time.Unix(1714086770, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe9, 0x3a, 0x4d, 0x93, 0x3, 0x91, 0x9, 0xc0, 0xdb, 0x60, 0x22, 0x29, 0xcb, 0x5c, 0x34, 0xe9, 0xdb, 0x58, 0x24, 0x1f, 0xdb, 0x6f, 0xe0, 0x4b, 0x4f, 0xfd, 0x3f, 0x95, 0x19, 0xac, 0x99, 0x6}}
	return a, nil
}

var __000002_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x41\x6b\x84\x30\x10\x85\xef\xfe\x8a\x39\x2a\x78\xb0\xf4\xe8\x69\xaa\x63\x1b\x9a\xb6\x32\xc6\x52\x4f\x45\x8c\x49\xa5\xd9\xb8\xb8\xfa\xff\x17\x16\x59\x50\xdc\xeb\xf7\xde\xe3\x7d\x39\x7f\x95\xa0\xf0\x45\x12\x88\x02\xe8\x47\x54\xaa\x82\xcb\xdf\x38\xcd\xbf\x6e\xf4\xb6\x66\x99\x06\x87\x9d\xce\xd8\x34\xc8\x98\x50\xd1\x9a\x6d\x56\xe1\xa0\xa1\x22\x16\x28\xa1\x64\xf1\x81\xdc\xc0\x3b\x35\xf1\x5a\x5a\x26\x07\xdf\xc8\xd9\x1b\x72\xf8\x94\x24\x51\x0c\xeb\x6c\x47\xe7\xf1\xbf\xf7\x77\xf6\x7c\x63\xba\x77\x85\x6b\x2d\x88\x4f\x45\xaf\xc4\x90\x53\x81\xb5\x54\x90\x44\x3b\x9f\xce\x58\x78\xa4\x61\x5c\x6b\x79\xf1\xa8\xf5\xb4\xbb\x6c\xcf\xc3\x71\x60\x9c\x3f\x6d\x50\x94\x5e\x03\x00\x00\xff\xff\x4b\x59\xac\x82\x3d\x01\x00\x00")

func _000002_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_init_mgUpSql,
		"000002_init_mg.up.sql",
	)
}

func _000002_init_mgUpSql() (*asset, error) {
	bytes, err := _000002_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_init_mg.up.sql", size: 317, mode: os.FileMode(0644), modTime: time.Unix(1714086770, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe9, 0x3a, 0x4d, 0x93, 0x3, 0x91, 0x9, 0xc0, 0xdb, 0x60, 0x22, 0x29, 0xcb, 0x5c, 0x34, 0xe9, 0xdb, 0x58, 0x24, 0x1f, 0xdb, 0x6f, 0xe0, 0x4b, 0x4f, 0xfd, 0x3f, 0x95, 0x19, 0xac, 0x99, 0x6}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init_mg.down.sql": _000001_init_mgDownSql,
	"000001_init_mg.up.sql":   _000001_init_mgUpSql,
	"000002_init_mg.down.sql": _000002_init_mgDownSql,
	"000002_init_mg.up.sql":   _000002_init_mgUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init_mg.down.sql": {_000001_init_mgDownSql, map[string]*bintree{}},
	"000001_init_mg.up.sql":   {_000001_init_mgUpSql, map[string]*bintree{}},
	"000002_init_mg.down.sql": {_000002_init_mgDownSql, map[string]*bintree{}},
	"000002_init_mg.up.sql":   {_000002_init_mgUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
