// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 000001_init_mg.down.sql (265B)
// 000001_init_mg.up.sql (265B)

package bindata

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_init_mgDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8d\xbf\x0e\x82\x30\x10\x87\x77\x9e\xe2\x46\x48\x18\x70\x66\x3a\xf1\xd4\x46\x54\x72\x54\x23\x93\x51\x9a\x56\x93\x5a\x92\x2a\x3e\xbf\x4b\x17\x1a\x59\x7f\x7f\xbe\x6f\xc5\xc7\x06\x24\x2e\x6b\x02\xb1\x06\xba\x88\x56\xb6\xf0\x7e\x0c\xfe\x73\xb5\x83\x33\x27\xae\xcb\xe4\xef\xa6\xd7\xa6\x4c\x2a\x26\x94\x14\xba\xc9\x2b\x7d\x2a\x10\x07\x49\x1b\x62\x68\x58\xec\x91\x3b\xd8\x51\x97\x87\xd5\xe8\x2d\x9c\x91\xab\x2d\x72\xba\x28\x8a\x2c\x87\xf0\x9b\xa4\x59\x64\xe8\xb5\x81\x59\xb0\xb6\x37\xc3\xa3\x43\xa5\x7c\x84\xfe\xde\x5d\x94\x68\xeb\x5e\x91\xe9\x17\x00\x00\xff\xff\x1f\x52\x8e\xbc\x09\x01\x00\x00")

func _000001_init_mgDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgDownSql,
		"000001_init_mg.down.sql",
	)
}

func _000001_init_mgDownSql() (*asset, error) {
	bytes, err := _000001_init_mgDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.down.sql", size: 265, mode: os.FileMode(0644), modTime: time.Unix(1711573214, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb9, 0x69, 0xe8, 0xf0, 0x22, 0xa9, 0x63, 0xfc, 0xe5, 0x5d, 0xc8, 0x7a, 0x83, 0x5b, 0x95, 0x5e, 0x22, 0x5, 0xd9, 0x63, 0xb6, 0x11, 0x24, 0x41, 0xcd, 0x37, 0x8c, 0x98, 0x86, 0xd5, 0x9, 0x28}}
	return a, nil
}

var __000001_init_mgUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8d\xbf\x0e\x82\x30\x10\x87\x77\x9e\xe2\x46\x48\x18\x70\x66\x3a\xf1\xd4\x46\x54\x72\x54\x23\x93\x51\x9a\x56\x93\x5a\x92\x2a\x3e\xbf\x4b\x17\x1a\x59\x7f\x7f\xbe\x6f\xc5\xc7\x06\x24\x2e\x6b\x02\xb1\x06\xba\x88\x56\xb6\xf0\x7e\x0c\xfe\x73\xb5\x83\x33\x27\xae\xcb\xe4\xef\xa6\xd7\xa6\x4c\x2a\x26\x94\x14\xba\xc9\x2b\x7d\x2a\x10\x07\x49\x1b\x62\x68\x58\xec\x91\x3b\xd8\x51\x97\x87\xd5\xe8\x2d\x9c\x91\xab\x2d\x72\xba\x28\x8a\x2c\x87\xf0\x9b\xa4\x59\x64\xe8\xb5\x81\x59\xb0\xb6\x37\xc3\xa3\x43\xa5\x7c\x84\xfe\xde\x5d\x94\x68\xeb\x5e\x91\xe9\x17\x00\x00\xff\xff\x1f\x52\x8e\xbc\x09\x01\x00\x00")

func _000001_init_mgUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_init_mgUpSql,
		"000001_init_mg.up.sql",
	)
}

func _000001_init_mgUpSql() (*asset, error) {
	bytes, err := _000001_init_mgUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init_mg.up.sql", size: 265, mode: os.FileMode(0644), modTime: time.Unix(1711573224, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xb9, 0x69, 0xe8, 0xf0, 0x22, 0xa9, 0x63, 0xfc, 0xe5, 0x5d, 0xc8, 0x7a, 0x83, 0x5b, 0x95, 0x5e, 0x22, 0x5, 0xd9, 0x63, 0xb6, 0x11, 0x24, 0x41, 0xcd, 0x37, 0x8c, 0x98, 0x86, 0xd5, 0x9, 0x28}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init_mg.down.sql": _000001_init_mgDownSql,
	"000001_init_mg.up.sql":   _000001_init_mgUpSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init_mg.down.sql": {_000001_init_mgDownSql, map[string]*bintree{}},
	"000001_init_mg.up.sql":   {_000001_init_mgUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
