DROP TABLE IF EXISTS short_longURL;
DROP TABLE IF EXISTS cfg;
CREATE TABLE short_longURL(id SERIAL PRIMARY KEY, short_url VARCHAR(100), longURL VARCHAR(100));
CREATE TABLE cfg (id SERIAL PRIMARY KEY, flagRunAddr VARCHAR(100), apiRunAddr VARCHAR(100), flnm VARCHAR(100));