DROP TABLE IF EXISTS short_longURL;
DROP TABLE IF EXISTS cfg;
CREATE TABLE short_longURL(id INTEGER PRIMARY KEY, short_url VARCHAR(100), longURL VARCHAR(100));
CREATE TABLE cfg (id INTEGER PRIMARY KEY, flagRunAddr VARCHAR(100), vbn VARCHAR(100), flnm VARCHAR(100));